[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = "card.lua"
position = "before"
pattern = 'self:set_ability(center, true)'
match_indent = false
payload = '''
	if self.params.infinifusion then self.infinifusion = self.params.infinifusion end
	if self.params.infus_editions then self.infus_editions = self.params.infus_editions end
	if self.params.infus_api then
		self.infinifusion_api = self.params.infus_api
		self.infinifusion_api_checked = true
		self.params.infus_api = nil
	end
'''

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
position = "before"
pattern = 'new_card:set_ability(other.config.center)'
match_indent = false
payload = '''if other.infinifusion then new_card.infinifusion = copy_table(other.infinifusion) end
if other.infinifusion_api_checked then 
	new_card.infinifusion_api_checked = other.infinifusion_api_checked
	new_card.infinifusion_api = other.infinifusion_api
end
'''

[[patches]]
[patches.pattern]
target = "card.lua"
position = "before"
pattern = "(self.ability.set == 'Joker' and {G.C.RARITY[self.config.center.rarity]}) or"
match_indent = false
payload = "self.infinifusion and {InfiniteFusion.badge_colour} or"

